sudo: false
language: node_js
node_js:
  - "5"
  - "6"
  - "7"
  - "8"
os:
  - linux
install:
  - npm install
script:
  - npm test
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
