language: node_js
node_js:
  - "8"
  - "9"
install:
  - npm install
script:
  - npm test
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
notifications:
  email:
    on_success: never
    on_failure: always